[ARC-1921]Feature/starting app design
andguladzeshio/TaskPlanner pull request #2
Opened 2021-11-23 15:45 UTC by andguladzeshio

https://spaceneobank.atlassian.net/browse/ARC-1921

2021-11-24 13:07 UTC, giorgiqemoklidze requested changes

2021-11-24 13:07 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/views/CustomBackgroundRect.kt
> +
კონსტანტ ცვლადებში გაიტანე

2021-11-24 13:07 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/views/CustomBackgroundRect.kt
> +        context.theme.obtainStyledAttributes(attrs, R.styleable.CustomBackgroundRect, 0, 0).apply {
აქაც კონსტანტ ცვლადები გამოიყენე

2021-11-24 13:07 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/views/CustomBackgroundRect.kt
> +            cornerRadius = if (!setted) getDimensionPixelSize(R.styleable.CustomBackgroundRect_radius, 200).toFloat() else cornerRadius
აქაც

2021-11-24 13:07 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/views/CustomBackgroundRect.kt
> +            overFlow = getDimensionPixelSize(R.styleable.CustomBackgroundRect_overflow, 30).toFloat()
აქაც კონსტანტ ცვლადი

2021-11-24 13:30 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/views/CustomBackgroundRect.kt
> +
done

2021-11-24 13:30 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/views/CustomBackgroundRect.kt
> +            overFlow = getDimensionPixelSize(R.styleable.CustomBackgroundRect_overflow, 30).toFloat()
done

2021-11-25 07:50 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-25 08:38 UTC, giorgiqemoklidze approved these changes

2021-11-25 08:40 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-25 08:56 UTC, AnaRusadze approved these changes

2021-11-26 12:28 UTC, merged