[ARC-1922]Feature/app design part2
andguladzeshio/TaskPlanner pull request #3
Opened 2021-11-26 12:31 UTC by andguladzeshio

https://spaceneobank.atlassian.net/browse/ARC-1922

2021-11-27 06:54 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-27 10:22 UTC, giorgiqemoklidze approved these changes

2021-11-29 14:15 UTC, AnaRusadze requested changes

2021-11-29 14:15 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/login_screen/AuthorizationFragment.kt
> +        }
with binding

2021-11-29 14:15 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_authorization.xml
> +        app:hint="Enter Profession"
სტრინგების რესურსში

2021-11-29 14:15 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_home_screen.xml
> +        tools:text="Peter Parker"
ctrl + alt + l

2021-11-29 14:15 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_new_project.xml
> +        app:hint="Project Title"
სტრინგების რესურსი

2021-11-29 14:15 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_new_project.xml
> +        app:hint="Estimated Start Date"
სტრინგების რესურსი

2021-11-29 14:15 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_new_project.xml
> +        app:hint="Estimated End Date"
სტრინგების რესურსი

2021-11-29 14:15 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
ეს წაშალე

2021-11-29 14:15 UTC, AnaRusadze commented on app/src/main/res/xml/fragment_authorization_scene.xml
> +            android:id="@+id/customRect"
ერთი და იგივე აიდი არ გიწითლებს?

2021-11-29 14:42 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/login_screen/AuthorizationFragment.kt
> +        }
done

2021-11-29 14:43 UTC, andguladzeshio commented on app/src/main/res/layout/fragment_home_screen.xml
> +        tools:text="Peter Parker"
done

2021-11-29 14:43 UTC, andguladzeshio commented on app/src/main/res/layout/fragment_new_project.xml
> +        app:hint="Project Title"
done

2021-11-29 14:43 UTC, andguladzeshio commented on app/src/main/res/layout/fragment_new_project.xml
> +        app:hint="Estimated Start Date"
done

2021-11-29 14:43 UTC, andguladzeshio commented on app/src/main/res/layout/fragment_new_project.xml
> +        app:hint="Estimated End Date"
done

2021-11-29 14:43 UTC, andguladzeshio commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
done

2021-11-29 14:44 UTC, andguladzeshio commented on app/src/main/res/xml/fragment_authorization_scene.xml
> +            android:id="@+id/customRect"
არაა სხვადასხვა კონსტრეინტში როა ეტყობა მაგიტო

2021-12-01 07:56 UTC, AnaRusadze approved these changes

2021-12-01 07:56 UTC, merged