[ARC-1923]Feature/firebase config
andguladzeshio/TaskPlanner pull request #5
Opened 2021-12-01 12:29 UTC by andguladzeshio

https://spaceneobank.atlassian.net/browse/ARC-1923

2021-12-02 07:43 UTC, AnaRusadze requested changes

2021-12-02 07:43 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/authentication/login_screen/AuthorizationViewModel.kt
> +        if (email.trim().isEmpty() || password.trim().length < 6){
ექვსი კონსტანტაა

2021-12-02 07:43 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/authentication/login_screen/AuthorizationViewModel.kt
> +        if (email.trim().isEmpty() || password.trim().length < 6){
email.isBlank ჯობია

2021-12-02 07:43 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/splash_screen/SplashScreenViewModel.kt
> +    fun isUserLogged() = repository.getCurrentUser() != null
ფუნქციის სახელი ისეთია, რომ ბულიანს ელოდები. getCurrentUser დაარქვი მასაც, რომ იუზერი წამოიღო ან ნალი

2021-12-02 07:43 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/authentication/login_screen/AuthorizationFragment.kt
> +                    is AuthStates.Error -> Toast.makeText(requireContext(), it.message, Toast.LENGTH_SHORT).show()
ტოუსტის ექსთენშენი გააკეთე

2021-12-02 07:43 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/authentication/registration_screen/RegistrationViewModel.kt
> +        if (email.trim().isEmpty() || password.trim().length < 6) {
აქაც

2021-12-02 07:43 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_registration.xml
> +        android:id="@+id/appCompatImageView"
რისი იმიჯია მაგის აღნიშვნელი უნდა იყოს აიდის სახელი, ამ შემთხვევაში ლოგოსი

2021-12-02 07:43 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_registration.xml
> +        android:id="@+id/appCompatButton"
აქაც, ფუნქციის სახელი უნდა ერქვას ღილაკს, ამ შემთხვევაში ლოგინის

2021-12-02 07:43 UTC, AnaRusadze commented on app/src/main/res/xml/fragment_authorization_scene.xml
> +            android:id="@+id/appCompatImageView"
რატო შეცვალე?

2021-12-02 08:42 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/authentication/login_screen/AuthorizationViewModel.kt
> +        if (email.trim().isEmpty() || password.trim().length < 6){
done

2021-12-02 08:42 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/splash_screen/SplashScreenViewModel.kt
> +    fun isUserLogged() = repository.getCurrentUser() != null
ბულიანს აბრუნებს ამოწმებს არის თუ არა იუზერი დალოგინებული

2021-12-02 08:42 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/authentication/login_screen/AuthorizationFragment.kt
> +                    is AuthStates.Error -> Toast.makeText(requireContext(), it.message, Toast.LENGTH_SHORT).show()
done

2021-12-02 08:42 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/authentication/registration_screen/RegistrationViewModel.kt
> +        if (email.trim().isEmpty() || password.trim().length < 6) {
done

2021-12-02 08:43 UTC, andguladzeshio commented on app/src/main/res/layout/fragment_registration.xml
> +        android:id="@+id/appCompatImageView"
done

2021-12-02 08:43 UTC, andguladzeshio commented on app/src/main/res/layout/fragment_registration.xml
> +        android:id="@+id/appCompatButton"
done

2021-12-02 08:44 UTC, andguladzeshio commented on app/src/main/res/xml/fragment_authorization_scene.xml
> +            android:id="@+id/appCompatImageView"
არ ვიცი ალბათ რომ ჩავმერჯე მაგის ბრალია

2021-12-02 08:49 UTC, GiorgiMamagulashvili16 approved these changes

2021-12-02 11:36 UTC, giorgiqemoklidze approved these changes

2021-12-06 15:07 UTC, AnaRusadze approved these changes

2021-12-06 15:07 UTC, merged