[ARC-1923]Feature/firebase config part2
andguladzeshio/TaskPlanner pull request #6
Opened 2021-12-08 10:01 UTC by andguladzeshio

https://spaceneobank.atlassian.net/browse/ARC-1923

2021-12-08 12:52 UTC, AnaRusadze requested changes

2021-12-08 12:52 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/model/User.kt
> +    var uid: String? = null
uid val უნდა იყოს და ზევით უნდა ეწეროს

2021-12-08 12:52 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/repository/user/UserRepository.kt
> +    fun getUserPfp(uid: String): Task<ByteArray>
PFp?

2021-12-08 12:52 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/util/FirebaseConstants.kt
> +    const val ONE_MEGABYTE = 1024L * 1024L
ეს რისთვის გჭირდება?

2021-12-08 13:16 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/model/User.kt
> +    var uid: String? = null
done

2021-12-08 13:16 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/repository/user/UserRepository.kt
> +    fun getUserPfp(uid: String): Task<ByteArray>
profilePicture 😄

2021-12-08 13:17 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/util/FirebaseConstants.kt
> +    const val ONE_MEGABYTE = 1024L * 1024L
მაქსიმალური ჩამოტვირთვის საიზი ჭირდებოდა ფაიერბეიზს

2021-12-08 13:17 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/util/FirebaseConstants.kt
> +    const val ONE_MEGABYTE = 1024L * 1024L
შეიძლება დაახლ 5 მეგაბაიტამდე ავწიო ან 10 რო არ დაიქრაშოს რამე ფოტოზე

2021-12-08 13:18 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/util/FirebaseConstants.kt
> +    const val ONE_MEGABYTE = 1024L * 1024L
მარა მგონი 1 საკმარისია

2021-12-08 14:03 UTC, giorgiqemoklidze approved these changes

2021-12-13 08:41 UTC, AnaRusadze approved these changes

2021-12-13 08:41 UTC, merged