[ARC-1923]Feature/firebase config part4
andguladzeshio/TaskPlanner pull request #8
Opened 2021-12-16 07:34 UTC by andguladzeshio

https://spaceneobank.atlassian.net/browse/ARC-1923

2021-12-21 09:17 UTC, AnaRusadze requested changes

2021-12-21 09:17 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/new_project_screen/NewProjectFragment.kt
> +    }
with(binding) დაამატე და ყველგან მოაშორებ

2021-12-21 09:17 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/new_task_screen/NewTaskFragment.kt
> +
აქ რამე უნდა ეწეროს თუ დაგრჩა?

2021-12-21 09:17 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/util/InfoValidator.kt
> +        val isPasswordValid = user.password.length >= 6 && user.password.isNotBlank()
ექვსიც კონსტანტა იყოს

2021-12-21 09:59 UTC, AnaRusadze requested changes

2021-12-21 09:59 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/authentication/login_screen/AuthorizationFragment.kt
> +                ).show()
ტოუსტის ექსთენშენი

2021-12-22 09:41 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/home_screen/HomeScreenFragment.kt
> +            binding.customBackgroundRect.setOnClickListener { // before adding logout button to be able to log out
done

2021-12-22 09:41 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/home_screen/HomeScreenFragment.kt
> +            binding.addProjectButton.setOnClickListener {
done

2021-12-22 09:41 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/new_project_screen/NewProjectFragment.kt
> +    }
done

2021-12-22 09:41 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/new_task_screen/NewTaskFragment.kt
> +
done

2021-12-22 09:41 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/util/InfoValidator.kt
> +        val isPasswordValid = user.password.length >= 6 && user.password.isNotBlank()
done

2021-12-22 09:41 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/ui/authentication/login_screen/AuthorizationFragment.kt
> +                ).show()
done

2021-12-27 08:10 UTC, AnaRusadze approved these changes

2021-12-27 08:11 UTC, merged