Feature/firebase config part5/arc 1924
andguladzeshio/TaskPlanner pull request #9
Opened 2021-12-27 10:21 UTC by andguladzeshio

https://spaceneobank.atlassian.net/browse/ARC-1924

2021-12-28 08:37 UTC, giorgiqemoklidze approved these changes

2021-12-28 13:22 UTC, GiorgiMamagulashvili16 approved these changes

2022-01-11 14:57 UTC, AnaRusadze requested changes

2022-01-11 14:57 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/model/ProjectTask.kt
> +    val progress: String = Progress.TODO
change name of "progress" to status, also change enum name to Status

2022-01-11 14:57 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/util/Progress.kt
> +object Progress {
why did you change enum to object?

2022-01-12 07:01 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/model/ProjectTask.kt
> +    val progress: String = Progress.TODO
done

2022-01-12 07:02 UTC, andguladzeshio commented on app/src/main/java/com/example/taskplanner/util/Progress.kt
> +object Progress {
changed back to enum

2022-01-12 08:04 UTC, AnaRusadze approved these changes

2022-01-12 08:04 UTC, merged